import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import React from "react";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  favorite,
  daily,
  auth,
}: Readonly<{
  children: React.ReactNode;
  favorite: React.ReactNode;
  daily: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="w-full h-30 flex justify-between items-center box-border p-8">
          <div>其他</div>
          <div className="h-14">
            <Image
              src="/logo.png"
              width={400}
              height={160}
              alt="LOGO"
              priority
              style={{ objectFit: "contain", height: "100%" }}
            />
          </div>
          <Link href="/login">点击登录</Link>
        </nav>
        {children}
        {daily}
        {favorite}
        {auth}
      </body>
    </html>
  );
}
